[package]
name = "sunny"
version = "1.0.0"
edition = "2021"
authors = ["Val Cubeta"]
rust-version = "1.68"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
